// ─── The report-type registry — PURE, import-free ─────────────────────────────
//
// One row per report type. Previously this was FOUR parallel structures in
// reportService.js, all keyed by the same string:
//
//   REPORT_TYPES  (:44)  the valid-type list
//   TYPE_LABEL    (:45)  the human name
//   SCOPE_TYPES   (:58)  which device_types it can be scoped to
//   BUILDERS      (:729) the function that gathers the data
//
// Adding a type meant four edits, and each omission failed differently — three of them
// silently:
//
//   miss REPORT_TYPES → the type is rejected as invalid (loud, at least)
//   miss TYPE_LABEL   → the report title reads "undefined Report"
//   miss BUILDERS     → `BUILDERS[type] is not a function` inside build(), which is
//                       fire-and-forget, so the row just flips to `failed` with nothing
//                       on screen explaining why
//   miss SCOPE_TYPES  → treated as campus-wide, which is EXACTLY what `environment`
//                       relies on — so a forgotten entry is indistinguishable from a
//                       deliberate one
//
// That last case is why this is a registry rather than a convention: `scope: null` now
// states "campus-wide" outright instead of expressing it by absence.
//
// See audits/design-patterns-report-2026-08-25.md — P-08.

/**
 * @typedef {{ label: string, scope: string[] | null }} ReportTypeMeta
 * `scope: null` = campus-wide; scoping it to a device is rejected, not ignored.
 */

/** @type {Record<string, ReportTypeMeta>} */
export const REPORT_TYPE_META = {
  environment: {
    label: "Environment",
    // Describes the server room itself (one sensor cluster), so "which device" is not a
    // meaningful question.
    scope: null,
  },
  server: { label: "Server Metrics", scope: ["server"] },
  network: { label: "Network Traffic", scope: ["router", "mikrotik"] },
  ups: { label: "UPS Power", scope: ["ups"] },
  alerts: {
    label: "Alert History",
    scope: ["server", "router", "mikrotik", "ups", "aircon", "esp32"],
  },
  aircon: { label: "Aircon Activity", scope: ["aircon"] },
  forecast: {
    label: "Capacity Forecast",
    // A forecast can be narrowed to one device, but it spans three classes when unscoped
    // (disk, battery, link) — so every forecastable type is offered.
    scope: ["server", "router", "mikrotik", "ups"],
  },
};

/** Every valid report type. */
export const REPORT_TYPES = Object.keys(REPORT_TYPE_META);

/** type → human label. */
export const TYPE_LABEL = Object.fromEntries(
  REPORT_TYPES.map((t) => [t, REPORT_TYPE_META[t].label]),
);

/**
 * type → allowed device_types. Types with `scope: null` are ABSENT here, which is the
 * shape the existing callers test with `if (!allowed) throw …`.
 */
export const SCOPE_TYPES = Object.fromEntries(
  REPORT_TYPES.filter((t) => REPORT_TYPE_META[t].scope !== null).map((t) => [
    t,
    REPORT_TYPE_META[t].scope,
  ]),
);

// ─── Titles ──────────────────────────────────────────────────────────────────

/** `reports.title` is varchar(100). MySQL in non-strict mode truncates anything longer
 *  without complaining, which would clip a control number off the end. */
export const TITLE_MAX = 100;

/**
 * The title a report gets when nobody typed one.
 *
 * Shared by create() and titleWithReference so the two cannot drift: the latter decides
 * whether a title was AUTO-GENERATED by rebuilding this string and comparing it, and a
 * second copy of the format would quietly stop every default title matching.
 */
export function defaultTitle(type, deviceName) {
  return `${TYPE_LABEL[type] ?? type} Report${deviceName ? ` — ${deviceName}` : ""}`;
}

/**
 * Put the control number into an auto-generated title.
 *
 * Only an AUTO title is touched. Someone who typed "Q3 submission for the Dean" chose
 * those words, and appending to them would be editing a person's text — the number is
 * already on the document, in the list and in the detail drawer, so nothing is lost by
 * leaving their wording alone.
 *
 * Worth doing at all because the title is also the DOWNLOAD FILENAME. Without it a
 * folder of downloads reads "Server Metrics Report — meow's.pdf" several times over,
 * with no way to tell which filed document each one is.
 *
 * Detected by comparison rather than by a flag column, which would need a migration to
 * answer a question the data already answers. Someone who types the default string
 * verbatim also gets the number — the same thing they would have got by leaving the
 * field blank, so the false positive costs nothing.
 *
 * @param {{title: string, type: string, deviceName?: string|null}} report
 * @param {string|null} reference
 * @returns {string}
 */
export function titleWithReference({ title, type, deviceName }, reference) {
  if (!reference || !title) return title;
  if (title !== defaultTitle(type, deviceName)) return title;

  const suffix = ` (${reference})`;
  const room = TITLE_MAX - suffix.length;
  // Truncate the DESCRIPTION, never the number: a clipped device name is still readable,
  // a clipped control number is simply wrong. Only bites on a very long device name.
  const base = title.length > room ? `${title.slice(0, room - 1).trimEnd()}…` : title;
  return base + suffix;
}

/**
 * Fail at STARTUP if a type has no builder, rather than when someone finally generates
 * that report and it silently lands in `failed`.
 *
 * Called once at module load in reportService. Throwing here takes the backend down on
 * boot, which is the right trade: a registry/builder mismatch is a programming error
 * that a developer will see immediately, not a runtime condition to degrade around.
 */
export function assertBuildersComplete(builders) {
  const missing = REPORT_TYPES.filter((t) => typeof builders[t] !== "function");
  if (missing.length) {
    throw new Error(
      `reportTypes: no builder for report type(s): ${missing.join(", ")}. ` +
        `Add one to BUILDERS in reportService.js, or remove the type from REPORT_TYPE_META.`,
    );
  }
  const orphans = Object.keys(builders).filter((t) => !REPORT_TYPE_META[t]);
  if (orphans.length) {
    throw new Error(
      `reportTypes: builder(s) with no registry entry: ${orphans.join(", ")}. ` +
        `Add them to REPORT_TYPE_META or delete them.`,
    );
  }
  return true;
}

export default {
  REPORT_TYPE_META,
  REPORT_TYPES,
  TYPE_LABEL,
  SCOPE_TYPES,
  TITLE_MAX,
  defaultTitle,
  titleWithReference,
  assertBuildersComplete,
};
