import fs from "fs";
import path from "path";
import db from "../config/mysql.js";
import { queryClient, bucket } from "../config/influx.js";
import { toCSV, toPDFBuffer } from "./reportRenderer.js";
import emailService from "./emailService.js";
import analyticsService from "./analyticsService.js";

// Real reports: persisted in MySQL `reports`, with a CSV + PDF written to disk per
// report (file_path = stem, the route appends .csv/.pdf). Data is built on generate
// from the live stores — InfluxDB (sensor_environment / server_metrics /
// router_metrics + network_traffic / ups_metrics) and MySQL (alerts / aircon_logs) —
// then frozen into the saved files. Replaces the old data/db.js mock array.
//
// Every monitored stream has a report type. Six of the seven were already in the
// `reports.type` ENUM, which is why adding network + ups needed no migration; `forecast`
// was NOT, so it ships with migrations/2026-08-09_report_forecast_type.sql. Adding a type
// here without extending that ENUM does not fail loudly — MySQL in non-strict mode
// silently coerces the unknown value to '' and the report later fails to build with no
// obvious cause.
//
// Device names resolve through COALESCE(NULLIF(display_name, ''), device_name) — the same
// effective-name rule as agentService and the analytics engine — so a server renamed from
// the dashboard reads the same in a PDF as it does on screen. Aliased back to
// `device_name` so every consumer below is unchanged.

const REPORTS_DIR = path.resolve(process.cwd(), "reports");
fs.mkdirSync(REPORTS_DIR, { recursive: true });

// Injected once at startup (init) so the lifecycle can be pushed to browsers. Same
// pattern as notificationService / alertsService.
//
// Reports are SHARED, not per-user: `list()` returns every report regardless of who
// generated it, and the page has a "Generated by" column. So the three lifecycle
// events broadcast to every dashboard (io.emit) rather than to the creator's room —
// an admin watching the page sees a colleague's report appear, build and finish
// without refreshing. Only the toast is creator-specific, and the page decides that
// by comparing `generatedBy` (see Reports.tsx).
let _io = null;
function init(io) {
  _io = io;
}

export const REPORT_TYPES = ["environment", "server", "network", "ups", "alerts", "aircon", "forecast"];
const TYPE_LABEL = {
  environment: "Environment",
  server: "Server Metrics",
  network: "Network Traffic",
  ups: "UPS Power",
  alerts: "Alert History",
  aircon: "Aircon Activity",
  forecast: "Capacity Forecast",
};

// Which device_type a report of each kind can be scoped to. `environment` is absent
// on purpose: it describes the server room itself (one sensor cluster), so "which
// device" is not a meaningful question — scoping it is rejected rather than ignored.
export const SCOPE_TYPES = {
  server: ["server"],
  network: ["router", "mikrotik"],
  ups: ["ups"],
  aircon: ["aircon"],
  alerts: ["server", "router", "mikrotik", "ups", "aircon", "esp32"],
  // A forecast can be narrowed to one device, but it spans three classes when unscoped
  // (disk, battery, link) — so every forecastable type is offered.
  forecast: ["server", "router", "mikrotik", "ups"],
};

function badRequest(msg) {
  const err = new Error(msg);
  err.status = 400;
  return err;
}

// The ONLY user-supplied value that reaches a Flux query string. Everything else in
// these queries is a literal, which is what keeps the whitelist promise in
// report-page.md §5 true. Validated as a positive integer, so it cannot carry Flux
// syntax; create() also validates at the boundary and stores it in an INT column, so
// this is the second of two gates.
function fluxDeviceFilter(deviceId) {
  if (deviceId == null) return "";
  const id = Number(deviceId);
  if (!Number.isInteger(id) || id <= 0) throw badRequest("Invalid device id.");
  return `|> filter(fn: (r) => r.device_id == "${id}")`;
}

// ─── Influx helper ──────────────────────────────────────────────────────────
// Whitelisted Flux only (no user strings interpolated) → no injection surface.
function fluxRows(flux) {
  return new Promise((resolve, reject) => {
    const out = [];
    queryClient.queryRows(flux, {
      next(row, tableMeta) {
        out.push(tableMeta.toObject(row));
      },
      error: reject,
      complete() {
        resolve(out);
      },
    });
  });
}

const num = (v, d = 1) => (typeof v === "number" && !Number.isNaN(v) ? +v.toFixed(d) : null);
const dayKey = (iso) => String(iso).slice(0, 10);
// Decimal GB, the convention for link throughput (not GiB).
const gb = (bytes) => +((Number(bytes) || 0) / 1e9).toFixed(2);

// ─── Data builders (return the normalized report payload) ────────────────────
async function buildEnvironment(start, stop) {
  const fields = `r._field == "temperature" or r._field == "humidity" or r._field == "mq2_1_ppm" or r._field == "mq2_2_ppm"`;
  const q = (fn) => `
    from(bucket: "${bucket}")
      |> range(start: ${start.toISOString()}, stop: ${stop.toISOString()})
      |> filter(fn: (r) => r._measurement == "sensor_environment")
      |> filter(fn: (r) => ${fields})
      |> aggregateWindow(every: 1d, fn: ${fn}, timeSrc: "_start", createEmpty: false)
      |> pivot(rowKey: ["_time"], columnKey: ["_field"], valueColumn: "_value")`;

  const [means, maxes, mins] = await Promise.all([
    fluxRows(q("mean")),
    fluxRows(q("max")),
    fluxRows(q("min")),
  ]);

  const byDay = new Map();
  const slot = (d) => {
    if (!byDay.has(d)) byDay.set(d, { date: d });
    return byDay.get(d);
  };
  for (const r of means) {
    const s = slot(dayKey(r._time));
    s.avgTemp = num(r.temperature);
    s.avgHum = num(r.humidity, 0);
  }
  for (const r of maxes) {
    const s = slot(dayKey(r._time));
    s.maxTemp = num(r.temperature);
    s.maxGas = num(Math.max(r.mq2_1_ppm ?? 0, r.mq2_2_ppm ?? 0), 0);
  }
  for (const r of mins) {
    const s = slot(dayKey(r._time));
    s.minTemp = num(r.temperature);
  }

  const days = [...byDay.values()].sort((a, b) => b.date.localeCompare(a.date));
  const temps = days.map((d) => d.avgTemp).filter((v) => v != null);
  const overallAvg = temps.length ? +(temps.reduce((a, b) => a + b, 0) / temps.length).toFixed(1) : null;
  const peakTemp = days.reduce((m, d) => (d.maxTemp != null && d.maxTemp > m ? d.maxTemp : m), -Infinity);
  const peakGas = days.reduce((m, d) => (d.maxGas != null && d.maxGas > m ? d.maxGas : m), -Infinity);

  return {
    summary: [
      { label: "Days covered", value: days.length },
      { label: "Avg temperature", value: overallAvg != null ? `${overallAvg} °C` : "—" },
      { label: "Peak temperature", value: Number.isFinite(peakTemp) ? `${peakTemp} °C` : "—" },
      { label: "Peak gas", value: Number.isFinite(peakGas) ? `${peakGas} ppm` : "—" },
    ],
    table: {
      columns: ["Date", "Avg Temp °C", "Max Temp °C", "Min Temp °C", "Avg Hum %", "Peak Gas ppm"],
      rows: days.map((d) => [
        d.date, d.avgTemp ?? "—", d.maxTemp ?? "—", d.minTemp ?? "—", d.avgHum ?? "—", d.maxGas ?? "—",
      ]),
    },
  };
}

async function buildServer(start, stop, deviceId) {
  const fields = `r._field == "cpu_percent" or r._field == "mem_percent" or r._field == "disk_percent"`;
  const scope = fluxDeviceFilter(deviceId);
  const q = (fn) => `
    from(bucket: "${bucket}")
      |> range(start: ${start.toISOString()}, stop: ${stop.toISOString()})
      |> filter(fn: (r) => r._measurement == "server_metrics")
      ${scope}
      |> filter(fn: (r) => ${fields})
      |> group(columns: ["device_id", "_field"])
      |> ${fn}()`;

  const [means, maxes] = await Promise.all([fluxRows(q("mean")), fluxRows(q("max"))]);

  const byDev = new Map();
  const slot = (id) => {
    if (!byDev.has(id)) byDev.set(id, { device_id: id });
    return byDev.get(id);
  };
  const F = { cpu_percent: "Cpu", mem_percent: "Mem", disk_percent: "Disk" };
  for (const r of means) slot(r.device_id)[`avg${F[r._field]}`] = num(r._value, 0);
  for (const r of maxes) slot(r.device_id)[`max${F[r._field]}`] = num(r._value, 0);

  // Resolve device_id → name from MySQL.
  const [devices] = await db.query(
    "SELECT device_id, COALESCE(NULLIF(display_name, ''), device_name) AS device_name FROM devices WHERE device_type = 'server'",
  );
  const nameOf = new Map(devices.map((d) => [String(d.device_id), d.device_name]));

  const rows = [...byDev.values()].sort((a, b) =>
    String(nameOf.get(a.device_id) ?? a.device_id).localeCompare(
      String(nameOf.get(b.device_id) ?? b.device_id),
    ),
  );

  return {
    summary: [
      { label: "Servers reporting", value: rows.length },
      {
        label: "Busiest CPU (avg)",
        // Influx keeps metrics for devices that have since been removed from MySQL,
        // so fall back to the id — the same "#id" the table shows, not a bare "?".
        value: rows.length
          ? (() => {
              const id = rows.reduce((m, r) => ((r.avgCpu ?? 0) > (m.avgCpu ?? 0) ? r : m)).device_id;
              return nameOf.get(id) ?? `#${id}`;
            })()
          : "—",
      },
    ],
    table: {
      columns: ["Server", "Avg CPU %", "Max CPU %", "Avg Mem %", "Max Mem %", "Avg Disk %", "Max Disk %"],
      rows: rows.map((r) => [
        nameOf.get(r.device_id) ?? `#${r.device_id}`,
        r.avgCpu ?? "—", r.maxCpu ?? "—", r.avgMem ?? "—", r.maxMem ?? "—", r.avgDisk ?? "—", r.maxDisk ?? "—",
      ]),
    },
  };
}

// ─── Network: SNMP routers + MikroTik ────────────────────────────────────────
// Both pollers write the SAME measurements — mikrotikPollerService reuses
// writeNetworkSample — so one builder covers every network device. The MySQL
// `device_type` is what separates a stock SNMP router from the MikroTik, and it
// rides along as a column rather than splitting the report in two.
async function buildNetwork(start, stop, deviceId) {
  const S = start.toISOString();
  const E = stop.toISOString();
  const scope = fluxDeviceFilter(deviceId);

  // Per-device gauges (same group()+aggregate shape as buildServer).
  const gauges = (fn) => `
    from(bucket: "${bucket}")
      |> range(start: ${S}, stop: ${E})
      |> filter(fn: (r) => r._measurement == "router_metrics")
      ${scope}
      |> filter(fn: (r) => r._field == "cpu_percent" or r._field == "mem_percent" or r._field == "connected_clients")
      |> group(columns: ["device_id", "_field"])
      |> ${fn}()`;

  // Byte/error counters are CUMULATIVE (design doc §5), so a mean is meaningless
  // here: increase() sums the non-negative deltas — a counter reset on reboot
  // reads as 0, not as terabytes — and last() takes the period total. A series
  // with a single sample yields no delta and so no row: correct, one poll can't
  // tell you a volume.
  const counters = `
    from(bucket: "${bucket}")
      |> range(start: ${S}, stop: ${E})
      |> filter(fn: (r) => r._measurement == "network_traffic")
      ${scope}
      |> filter(fn: (r) => r._field == "rx_bytes" or r._field == "tx_bytes" or r._field == "rx_errors" or r._field == "tx_errors")
      |> increase()
      |> last()`;

  const peakUtil = `
    from(bucket: "${bucket}")
      |> range(start: ${S}, stop: ${E})
      |> filter(fn: (r) => r._measurement == "network_traffic")
      ${scope}
      |> filter(fn: (r) => r._field == "utilization_pct")
      |> max()`;

  // link_up is a boolean → map to 1/0 so mean() reads as "share of polls the port
  // was up".
  const linkUp = `
    from(bucket: "${bucket}")
      |> range(start: ${S}, stop: ${E})
      |> filter(fn: (r) => r._measurement == "network_traffic")
      ${scope}
      |> filter(fn: (r) => r._field == "link_up")
      |> map(fn: (r) => ({ r with _value: if r._value then 1.0 else 0.0 }))
      |> mean()`;

  const [means, maxes, ctrs, utils, links] = await Promise.all([
    fluxRows(gauges("mean")),
    fluxRows(gauges("max")),
    fluxRows(counters),
    fluxRows(peakUtil),
    fluxRows(linkUp),
  ]);

  // Device facts + offline events from MySQL. `scoped` narrows both to one device
  // when the report is device-scoped (bound param, not interpolated).
  const scoped = deviceId != null;
  const [devices] = await db.query(
    `SELECT device_id, COALESCE(NULLIF(display_name, ''), device_name) AS device_name, device_type, location
       FROM devices
      WHERE device_type IN ('router', 'mikrotik')${scoped ? " AND device_id = ?" : ""}`,
    scoped ? [deviceId] : [],
  );
  const [offline] = await db.query(
    `SELECT a.device_id, COUNT(*) AS n
       FROM alerts a
       JOIN devices d ON d.device_id = a.device_id
      WHERE a.type = 'device_offline'
        AND d.device_type IN ('router', 'mikrotik')
        AND a.created_at BETWEEN ? AND ?
        ${scoped ? "AND a.device_id = ?" : ""}
      GROUP BY a.device_id`,
    scoped ? [start, stop, deviceId] : [start, stop],
  );
  const meta = new Map(devices.map((d) => [String(d.device_id), d]));
  const offlineOf = new Map(offline.map((r) => [String(r.device_id), Number(r.n)]));

  // ── Per-device roll-up ──
  const byDev = new Map();
  const dev = (id) => {
    if (!byDev.has(id)) byDev.set(id, { device_id: id, rxBytes: 0, txBytes: 0 });
    return byDev.get(id);
  };
  const G = { cpu_percent: "Cpu", mem_percent: "Mem", connected_clients: "Clients" };
  for (const r of means) dev(r.device_id)[`avg${G[r._field]}`] = num(r._value, 0);
  for (const r of maxes) dev(r.device_id)[`max${G[r._field]}`] = num(r._value, 0);

  // ── Per-interface breakdown ──
  const byIface = new Map();
  const iface = (r) => {
    const key = `${r.device_id}|${r.interface_name}`;
    if (!byIface.has(key)) {
      byIface.set(key, {
        device_id: r.device_id,
        name: r.interface_name || "—",
        label: r.location_label || "",
        rxBytes: 0, txBytes: 0, errors: 0,
      });
    }
    return byIface.get(key);
  };
  for (const r of ctrs) {
    const i = iface(r);
    const v = Number(r._value) || 0;
    if (r._field === "rx_bytes") { i.rxBytes = v; dev(r.device_id).rxBytes += v; }
    else if (r._field === "tx_bytes") { i.txBytes = v; dev(r.device_id).txBytes += v; }
    else i.errors += v; // rx_errors + tx_errors — one "did this link misbehave" number
  }
  for (const r of utils) iface(r).peakUtil = num(r._value, 0);
  for (const r of links) iface(r).upPct = num(Number(r._value) * 100, 0);

  const nameOf = (id) => meta.get(id)?.device_name ?? `#${id}`;
  // Influx outlives MySQL rows — a device deleted from the dashboard still has its
  // history here. Say "—" rather than guessing "Router" for one we can't identify.
  const kindOf = (id) => {
    const t = meta.get(id)?.device_type;
    return t === "mikrotik" ? "MikroTik" : t === "router" ? "Router" : "—";
  };

  const devRows = [...byDev.values()].sort((a, b) =>
    nameOf(a.device_id).localeCompare(nameOf(b.device_id)),
  );
  const ifaceRows = [...byIface.values()].sort(
    (a, b) => b.rxBytes + b.txBytes - (a.rxBytes + a.txBytes),
  );

  const totalBytes = devRows.reduce((s, d) => s + d.rxBytes + d.txBytes, 0);
  const totalErrors = ifaceRows.reduce((s, i) => s + i.errors, 0);
  const totalOffline = devRows.reduce((s, d) => s + (offlineOf.get(d.device_id) ?? 0), 0);
  const busiest = ifaceRows[0];

  return {
    summary: [
      { label: "Network devices reporting", value: devRows.length },
      { label: "Total traffic", value: totalBytes ? `${gb(totalBytes)} GB` : "—" },
      {
        label: "Busiest port",
        value: busiest
          ? `${nameOf(busiest.device_id)} ${busiest.name}${busiest.label ? ` (${busiest.label})` : ""} — ${gb(busiest.rxBytes + busiest.txBytes)} GB`
          : "—",
      },
      { label: "Link errors", value: totalErrors },
      { label: "Offline events", value: totalOffline },
    ],
    tables: [
      {
        title: "Devices",
        columns: ["Device", "Kind", "Avg CPU %", "Max CPU %", "Avg Mem %", "Avg Clients", "RX GB", "TX GB", "Offline"],
        rows: devRows.map((d) => [
          nameOf(d.device_id), kindOf(d.device_id),
          d.avgCpu ?? "—", d.maxCpu ?? "—", d.avgMem ?? "—", d.avgClients ?? "—",
          gb(d.rxBytes), gb(d.txBytes), offlineOf.get(d.device_id) ?? 0,
        ]),
      },
      {
        title: "Ports",
        columns: ["Device", "Port", "Location", "RX GB", "TX GB", "Peak Util %", "Errors", "Link Up %"],
        rows: ifaceRows.map((i) => [
          nameOf(i.device_id), i.name, i.label || "—",
          gb(i.rxBytes), gb(i.txBytes),
          i.peakUtil ?? "—", i.errors, i.upPct ?? "—",
        ]),
      },
    ],
  };
}

// ─── UPS power ───────────────────────────────────────────────────────────────
async function buildUps(start, stop, deviceId) {
  const S = start.toISOString();
  const E = stop.toISOString();
  const scope = fluxDeviceFilter(deviceId);

  const gauges = (fn) => `
    from(bucket: "${bucket}")
      |> range(start: ${S}, stop: ${E})
      |> filter(fn: (r) => r._measurement == "ups_metrics")
      ${scope}
      |> filter(fn: (r) =>
          r._field == "battery_charge_pct" or r._field == "runtime_remaining_min" or
          r._field == "load_pct" or r._field == "input_voltage" or
          r._field == "output_voltage" or r._field == "battery_voltage" or
          r._field == "temperature")
      |> group(columns: ["device_id", "_field"])
      |> ${fn}()`;

  // on_battery is a boolean. There is no "minutes on battery" that doesn't assume
  // a fixed poll interval, so we report the SHARE OF POLLS spent on battery —
  // honest whatever SNMP_POLL_INTERVAL_MS is set to. The event count below (from
  // the alerts table) is the "how many times did it happen" half.
  const onBattery = `
    from(bucket: "${bucket}")
      |> range(start: ${S}, stop: ${E})
      |> filter(fn: (r) => r._measurement == "ups_metrics")
      ${scope}
      |> filter(fn: (r) => r._field == "on_battery")
      |> map(fn: (r) => ({ r with _value: if r._value then 1.0 else 0.0 }))
      |> group(columns: ["device_id"])
      |> mean()`;

  const [means, mins, maxes, batt] = await Promise.all([
    fluxRows(gauges("mean")),
    fluxRows(gauges("min")),
    fluxRows(gauges("max")),
    fluxRows(onBattery),
  ]);

  const scoped = deviceId != null;
  const [devices] = await db.query(
    `SELECT device_id, COALESCE(NULLIF(display_name, ''), device_name) AS device_name, location FROM devices
      WHERE device_type = 'ups'${scoped ? " AND device_id = ?" : ""}`,
    scoped ? [deviceId] : [],
  );
  const [events] = await db.query(
    `SELECT a.device_id, a.type, COUNT(*) AS n
       FROM alerts a
       JOIN devices d ON d.device_id = a.device_id
      WHERE a.type IN ('ups_on_battery', 'device_offline')
        AND d.device_type = 'ups'
        AND a.created_at BETWEEN ? AND ?
        ${scoped ? "AND a.device_id = ?" : ""}
      GROUP BY a.device_id, a.type`,
    scoped ? [start, stop, deviceId] : [start, stop],
  );
  const meta = new Map(devices.map((d) => [String(d.device_id), d]));
  const evOf = new Map();
  for (const e of events) {
    const slot = evOf.get(String(e.device_id)) ?? { ups_on_battery: 0, device_offline: 0 };
    slot[e.type] = Number(e.n);
    evOf.set(String(e.device_id), slot);
  }

  const byDev = new Map();
  const dev = (id) => {
    if (!byDev.has(id)) byDev.set(id, { device_id: id });
    return byDev.get(id);
  };
  const F = {
    battery_charge_pct: "Charge",
    runtime_remaining_min: "Runtime",
    load_pct: "Load",
    input_voltage: "InV",
    output_voltage: "OutV",
    battery_voltage: "BattV",
    temperature: "Temp",
  };
  for (const r of means) dev(r.device_id)[`avg${F[r._field]}`] = num(r._value, 0);
  for (const r of mins) dev(r.device_id)[`min${F[r._field]}`] = num(r._value, 0);
  for (const r of maxes) dev(r.device_id)[`max${F[r._field]}`] = num(r._value, 0);
  for (const r of batt) dev(r.device_id).onBattPct = num(Number(r._value) * 100, 1);

  const nameOf = (id) => meta.get(id)?.device_name ?? `#${id}`;
  const rows = [...byDev.values()].sort((a, b) =>
    nameOf(a.device_id).localeCompare(nameOf(b.device_id)),
  );

  const lowest = (key) =>
    rows.reduce((m, r) => (r[key] != null && (m == null || r[key] < m) ? r[key] : m), null);
  const totalEv = (type) =>
    rows.reduce((s, r) => s + (evOf.get(r.device_id)?.[type] ?? 0), 0);
  const peakLoad = rows.reduce((m, r) => (r.maxLoad != null && r.maxLoad > m ? r.maxLoad : m), -Infinity);

  return {
    summary: [
      { label: "UPS units reporting", value: rows.length },
      { label: "Lowest battery", value: lowest("minCharge") != null ? `${lowest("minCharge")} %` : "—" },
      { label: "Shortest runtime", value: lowest("minRuntime") != null ? `${lowest("minRuntime")} min` : "—" },
      { label: "Peak load", value: Number.isFinite(peakLoad) ? `${peakLoad} %` : "—" },
      { label: "On-battery events", value: totalEv("ups_on_battery") },
      { label: "Offline events", value: totalEv("device_offline") },
    ],
    tables: [
      {
        title: "Battery & load",
        columns: ["UPS", "Location", "Avg Charge %", "Min Charge %", "Avg Runtime min", "Min Runtime min", "Avg Load %", "Max Load %", "On Battery %"],
        rows: rows.map((r) => [
          nameOf(r.device_id), meta.get(r.device_id)?.location ?? "—",
          r.avgCharge ?? "—", r.minCharge ?? "—",
          r.avgRuntime ?? "—", r.minRuntime ?? "—",
          r.avgLoad ?? "—", r.maxLoad ?? "—", r.onBattPct ?? "—",
        ]),
      },
      {
        title: "Voltage & events",
        columns: ["UPS", "Avg Input V", "Min Input V", "Max Input V", "Avg Output V", "Avg Battery V", "Max Temp °C", "On-battery", "Offline"],
        rows: rows.map((r) => [
          nameOf(r.device_id),
          r.avgInV ?? "—", r.minInV ?? "—", r.maxInV ?? "—",
          r.avgOutV ?? "—", r.avgBattV ?? "—", r.maxTemp ?? "—",
          evOf.get(r.device_id)?.ups_on_battery ?? 0,
          evOf.get(r.device_id)?.device_offline ?? 0,
        ]),
      },
    ],
  };
}

async function buildAlerts(start, stop, deviceId) {
  const scoped = deviceId != null;
  const [rows] = await db.query(
    `SELECT a.created_at, a.type, a.title, a.severity, a.status, a.metric_value,
            COALESCE(NULLIF(d.display_name, ''), d.device_name) AS device_name
       FROM alerts a
       LEFT JOIN devices d ON d.device_id = a.device_id
      WHERE a.created_at BETWEEN ? AND ?
        ${scoped ? "AND a.device_id = ?" : ""}
      ORDER BY a.created_at DESC`,
    scoped ? [start, stop, deviceId] : [start, stop],
  );
  const count = (sev) => rows.filter((r) => r.severity === sev).length;
  return {
    summary: [
      { label: "Total alerts", value: rows.length },
      { label: "Critical", value: count("critical") },
      { label: "Warning", value: count("warning") },
      { label: "Info", value: count("info") },
    ],
    table: {
      columns: ["Time", "Severity", "Device", "Title", "Value", "Status"],
      rows: rows.map((r) => [
        fmtRow(r.created_at),
        r.severity,
        r.device_name ?? "Server room",
        r.title,
        r.metric_value ?? "—",
        r.status,
      ]),
    },
  };
}

async function buildAircon(start, stop, deviceId) {
  const scoped = deviceId != null;
  const [rows] = await db.query(
    `SELECT l.created_at, l.action, l.reason, l.trigger_type, u.name AS user_name,
            COALESCE(NULLIF(d.display_name, ''), d.device_name) AS device_name
       FROM aircon_logs l
       LEFT JOIN devices d ON d.device_id = l.device_id
       LEFT JOIN users u   ON u.user_id   = l.user_id
      WHERE l.created_at BETWEEN ? AND ?
        ${scoped ? "AND l.device_id = ?" : ""}
      ORDER BY l.created_at DESC`,
    scoped ? [start, stop, deviceId] : [start, stop],
  );
  const manual = rows.filter((r) => r.trigger_type === "manual").length;
  return {
    summary: [
      { label: "Total actions", value: rows.length },
      { label: "Manual", value: manual },
      { label: "Auto", value: rows.length - manual },
    ],
    table: {
      columns: ["Time", "Unit", "Action", "Trigger", "By", "Reason"],
      rows: rows.map((r) => [
        fmtRow(r.created_at),
        r.device_name ?? "—",
        r.action,
        r.trigger_type,
        r.user_name ?? (r.trigger_type === "auto" ? "system" : "—"),
        r.reason,
      ]),
    },
  };
}

// ─── Forecast report ──────────────────────────────────────────────────────────
// The one FORWARD-looking report. Every other type summarises what happened inside the
// period; this one uses the period as the regression's lookback and reports what is
// projected to happen next — the artifact that justifies a purchase ("this volume fills
// in three weeks, here is the trend and how accurate our forecasts have been").
//
// Accuracy is included deliberately: a projection handed to a budget holder without its
// track record invites the obvious question, and answering it in the same PDF is the
// difference between a claim and evidence. See predictive-analytics.md §17.
async function buildForecast(start, stop, deviceId) {
  const spanDaysReq = Math.max(
    2,
    Math.round((new Date(stop).getTime() - new Date(start).getTime()) / 86_400_000),
  );

  const [disks, upses, links, accuracy] = await Promise.all([
    analyticsService.forecastDiskFull({ deviceId, lookbackDays: spanDaysReq }),
    analyticsService.forecastUpsBattery({ deviceId, lookbackDays: spanDaysReq }),
    analyticsService.forecastLinkSaturation({ deviceId, lookbackDays: spanDaysReq }),
    analyticsService.forecastAccuracy({ metric: "disk", deviceId, lookbackDays: spanDaysReq, horizonDays: 7 }),
  ]);

  const dated = (etaDays) =>
    etaDays == null ? "—" : new Date(Date.now() + etaDays * 86_400_000).toISOString().slice(0, 10);
  const eta = (v) => (v == null ? "—" : `${v} d`);
  const acting = [...disks, ...upses, ...links].filter((r) => r.advice);

  const tables = [
    {
      title: "Disk capacity",
      columns: ["Server", "Volume", "Current %", "Trend %/day", "ETA", "Projected full", "Confidence", "History d"],
      rows: disks.map((d) => [
        d.name, d.mount ?? "—", d.currentPercent ?? "—", d.slopePerDay ?? "—",
        d.status === "filling" ? eta(d.etaDays) : d.status,
        d.status === "filling" ? dated(d.etaDays) : "—",
        d.confidence, d.historyDays,
      ]),
    },
    {
      title: "UPS battery",
      columns: ["UPS", "Runtime min", "Trend min/day", "ETA to floor", "Replace by", "Confidence", "History d"],
      rows: upses.map((u) => [
        u.name, u.currentRuntimeMin ?? "—", u.slopePerDay ?? "—",
        u.status === "declining" ? eta(u.etaDays) : u.status,
        u.status === "declining" ? dated(u.etaDays) : "—",
        u.confidence, u.historyDays,
      ]),
    },
    {
      title: "Link saturation",
      columns: ["Device", "Interface", "Current %", "Trend %/day", "ETA", "Saturates by", "Confidence", "History d"],
      rows: links.map((l) => [
        l.name, l.interfaceLabel ? `${l.interfaceLabel} (${l.interface})` : l.interface,
        l.currentUtil ?? "—", l.slopePerDay ?? "—",
        l.status === "rising" ? eta(l.etaDays) : l.status,
        l.status === "rising" ? dated(l.etaDays) : "—",
        l.confidence, l.historyDays,
      ]),
    },
  ];

  if (acting.length) {
    tables.push({
      title: "Action needed",
      columns: ["Severity", "Recommendation"],
      rows: acting.map((r) => [r.advice.level, r.advice.message]),
    });
  }

  if (accuracy?.status === "ok") {
    tables.push({
      title: `Forecast accuracy (backtested, ${accuracy.horizonDays}-day horizon)`,
      columns: ["Server", "Typical miss", "Bias", "Worst miss", "Predictions checked"],
      rows: accuracy.devices.filter((d) => d.folds > 0).map((d) => [
        d.name, `±${d.mae}${accuracy.unit}`,
        `${(d.bias ?? 0) > 0 ? "over" : (d.bias ?? 0) < 0 ? "under" : "even"} ${Math.abs(d.bias ?? 0)}${accuracy.unit}`,
        `±${d.worst}${accuracy.unit}`, d.folds,
      ]),
    });
  }

  return {
    summary: [
      { label: "Lookback used", value: `${spanDaysReq} days` },
      { label: "Volumes projected to fill", value: disks.filter((d) => d.status === "filling").length },
      { label: "UPS batteries declining", value: upses.filter((u) => u.status === "declining").length },
      { label: "Interfaces trending up", value: links.filter((l) => l.status === "rising").length },
      { label: "Items needing action", value: acting.length },
      {
        label: "Forecast accuracy",
        value: accuracy?.overallMae == null ? "not yet verifiable" : `±${accuracy.overallMae}${accuracy.unit}`,
      },
    ],
    tables,
  };
}

function fmtRow(d) {
  const dt = d instanceof Date ? d : new Date(d);
  return Number.isNaN(dt.getTime()) ? "" : dt.toISOString().replace("T", " ").slice(0, 19);
}

const BUILDERS = {
  environment: buildEnvironment,
  server: buildServer,
  network: buildNetwork,
  ups: buildUps,
  alerts: buildAlerts,
  aircon: buildAircon,
  forecast: buildForecast,
};

// ─── Client shaping ──────────────────────────────────────────────────────────
function toClient(r) {
  const iso = (v) => (v instanceof Date ? v.toISOString() : v);
  return {
    id: r.report_id,
    title: r.title,
    type: r.type,
    status: r.status,
    generatedBy: r.generated_by,
    generatedByName: r.generated_by_name ?? null,
    // null = campus-wide. deviceName survives as NULL if the device is later
    // deleted (FK is ON DELETE SET NULL) — the report itself is still valid history.
    deviceId: r.device_id ?? null,
    deviceName: r.device_name ?? null,
    periodStart: iso(r.period_start),
    periodEnd: iso(r.period_end),
    createdAt: iso(r.created_at),
    hasFile: !!r.file_path,
  };
}

const BASE_SELECT = `
  SELECT r.report_id, r.title, r.type, r.device_id, r.status, r.generated_by, r.file_path,
         r.period_start, r.period_end, r.created_at,
         u.name AS generated_by_name, COALESCE(NULLIF(d.display_name, ''), d.device_name) AS device_name
    FROM reports r
    LEFT JOIN users u   ON u.user_id   = r.generated_by
    LEFT JOIN devices d ON d.device_id = r.device_id`;

// Devices a report of `type` can be scoped to. Driven by the SAME SCOPE_TYPES map
// that validates a submitted scope in create(), so the dropdown and the validator
// cannot drift apart. Empty array = this type is campus-wide (environment).
async function scopeOptions(type) {
  const allowed = SCOPE_TYPES[type];
  if (!allowed?.length) return [];
  const [rows] = await db.query(
    `SELECT device_id, COALESCE(NULLIF(display_name, ''), device_name) AS device_name, device_type, location
       FROM devices
      WHERE device_type IN (${allowed.map(() => "?").join(", ")})
      ORDER BY device_type, device_name`,
    allowed,
  );
  return rows.map((d) => ({
    id: d.device_id,
    name: d.device_name,
    type: d.device_type,
    location: d.location ?? null,
  }));
}

// ─── Public API ──────────────────────────────────────────────────────────────
async function list({ type, limit = 100 } = {}) {
  const n = Math.min(500, Math.max(1, parseInt(limit, 10) || 100));
  const where = [];
  const params = [];
  if (type && REPORT_TYPES.includes(type)) {
    where.push("r.type = ?");
    params.push(type);
  }
  const sql =
    BASE_SELECT +
    (where.length ? ` WHERE ${where.join(" AND ")}` : "") +
    ` ORDER BY r.created_at DESC LIMIT ${n}`;
  const [rows] = await db.query(sql, params);
  return rows.map(toClient);
}

async function getRaw(id) {
  const [[row]] = await db.query(`${BASE_SELECT} WHERE r.report_id = ? LIMIT 1`, [id]);
  return row ?? null;
}

// Generation is a two-step so the HTTP request doesn't have to wait for it: create()
// records the row as `pending` and returns immediately, build() does the slow work and
// flips the status. `reports.status` was always pending→generated|failed; before this
// split nothing could ever observe the pending state.
//
// The row IS the progress record, so a crash mid-build leaves a visible `pending` row
// rather than a silent gap.

async function create({ userId, type, title, periodStart, periodEnd, deviceId }) {
  if (!REPORT_TYPES.includes(type)) throw badRequest("Invalid report type.");

  const end = periodEnd ? new Date(periodEnd) : new Date();
  const start = periodStart ? new Date(periodStart) : new Date(end.getTime() - 7 * 24 * 3600 * 1000);
  if (Number.isNaN(start.getTime()) || Number.isNaN(end.getTime()) || start >= end) {
    throw badRequest("Invalid period: start must be before end.");
  }

  // Device scope: validated HERE, at the boundary, so everything downstream reads an
  // integer straight out of an INT column. A scope that doesn't match the report type
  // is rejected rather than silently dropped — "the MikroTik's environment report"
  // is a mistake worth surfacing, not quietly widening to the whole server room.
  let scopeId = null;
  let scopeName = null;
  if (deviceId != null && deviceId !== "") {
    const id = Number(deviceId);
    if (!Number.isInteger(id) || id <= 0) throw badRequest("Invalid device id.");
    const allowed = SCOPE_TYPES[type];
    if (!allowed) throw badRequest(`A ${TYPE_LABEL[type]} report covers the whole server room and cannot be scoped to one device.`);
    const [[dev]] = await db.query(
      "SELECT device_id, COALESCE(NULLIF(display_name, ''), device_name) AS device_name, device_type FROM devices WHERE device_id = ? LIMIT 1",
      [id],
    );
    if (!dev) throw badRequest("Device not found.");
    if (!allowed.includes(dev.device_type)) {
      throw badRequest(`"${dev.device_name}" is a ${dev.device_type}, which a ${TYPE_LABEL[type]} report does not cover.`);
    }
    scopeId = dev.device_id;
    scopeName = dev.device_name;
  }

  // Default title carries the scope, so a list of reports stays readable.
  const finalTitle =
    (title && title.trim()) ||
    `${TYPE_LABEL[type]} Report${scopeName ? ` — ${scopeName}` : ""}`;

  const [ins] = await db.query(
    `INSERT INTO reports (generated_by, title, type, device_id, status, period_start, period_end)
     VALUES (?, ?, ?, ?, 'pending', ?, ?)`,
    [userId, finalTitle.slice(0, 100), type, scopeId, start, end],
  );

  const created = toClient(await getRaw(ins.insertId));
  // Announce the pending row so every open Reports page shows it building — not just
  // the tab that asked for it.
  _io?.emit("reportCreated", created);
  return created;
}

// Build the dataset, write both files, flip the status. NEVER THROWS — it is called
// fire-and-forget from the route, where a rejection would be unhandled. Failure is
// reported the same way success is: the row status plus a `reportUpdated` push.
async function build(id) {
  const row = await getRaw(id);
  if (!row) return null;

  try {
    const start = new Date(row.period_start);
    const end = new Date(row.period_end);
    const payload = await BUILDERS[row.type](start, end, row.device_id ?? null);
    const report = {
      title: row.title,
      type: TYPE_LABEL[row.type] + (row.device_name ? ` — ${row.device_name}` : ""),
      periodStart: start,
      periodEnd: end,
      generatedAt: new Date(),
      summary: payload.summary,
      // A builder returns either one `table` or several titled `tables` — the
      // renderer normalizes both. Only ever one of the two is set.
      table: payload.table,
      tables: payload.tables,
    };

    const stem = `report-${id}`;
    fs.writeFileSync(path.join(REPORTS_DIR, `${stem}.csv`), toCSV(report), "utf8");
    fs.writeFileSync(path.join(REPORTS_DIR, `${stem}.pdf`), await toPDFBuffer(report));

    await db.query(
      "UPDATE reports SET status = 'generated', file_path = ? WHERE report_id = ?",
      [stem, id],
    );
  } catch (err) {
    console.error("[REPORTS] build failed:", err.message);
    try {
      await db.query("UPDATE reports SET status = 'failed' WHERE report_id = ?", [id]);
    } catch (dbErr) {
      // The DB is the only channel for "this failed" — if it's down too, log and
      // leave the row pending rather than crash the process.
      console.error("[REPORTS] could not mark failed:", dbErr.message);
    }
  }

  const final = toClient(await getRaw(id));
  if (final) _io?.emit("reportUpdated", final);
  return final;
}

// Create + build in one call. The route uses create/build separately so it can
// answer 202 immediately; this is for callers that genuinely want to wait.
async function generate(opts) {
  const created = await create(opts);
  return (await build(created.id)) ?? created;
}

// Resolve the on-disk file for a download. Returns { absPath, downloadName, report }
// or null. `report` rides along so the download route can audit whose report was
// exported — the actor and the author are often different people.
async function fileFor(id, format) {
  const fmt = String(format).toLowerCase();
  if (fmt !== "csv" && fmt !== "pdf") return null;
  const row = await getRaw(id);
  if (!row || !row.file_path || row.status !== "generated") return null;

  const absPath = path.join(REPORTS_DIR, `${path.basename(row.file_path)}.${fmt}`);
  if (!absPath.startsWith(REPORTS_DIR) || !fs.existsSync(absPath)) return null;

  // Download name = "<title> <start> to <end>.<fmt>", sanitized for the filesystem.
  const dateOnly = (d) => {
    const dt = d instanceof Date ? d : new Date(d);
    return Number.isNaN(dt.getTime()) ? "" : dt.toISOString().slice(0, 10);
  };
  const safeTitle = String(row.title || "report").replace(/[^\w.-]+/g, "_").replace(/_+/g, "_").slice(0, 60);
  const period =
    row.period_start && row.period_end
      ? `_${dateOnly(row.period_start)}_to_${dateOnly(row.period_end)}`
      : "";
  return { absPath, downloadName: `${safeTitle}${period}.${fmt}`, report: toClient(row) };
}

// Returns the removed report (truthy) or null. Returning the row rather than a
// boolean lets the route audit WHAT was deleted, not just that something was; every
// existing caller only tested truthiness, so this stays compatible.
async function remove(id, { silent = false } = {}) {
  const row = await getRaw(id);
  if (!row) return null;
  if (row.file_path) {
    for (const fmt of ["csv", "pdf"]) {
      const p = path.join(REPORTS_DIR, `${path.basename(row.file_path)}.${fmt}`);
      try {
        if (p.startsWith(REPORTS_DIR) && fs.existsSync(p)) fs.unlinkSync(p);
      } catch { /* best-effort cleanup */ }
    }
  }
  await db.query("DELETE FROM reports WHERE report_id = ?", [id]);
  // Third lifecycle event: without it, an admin's delete leaves a ghost row on every
  // other open page that 404s when clicked. `silent` is for the retention purge —
  // see purgeOld.
  if (!silent) _io?.emit("reportDeleted", { id: Number(id) });
  return toClient(row);
}

// Email an already-generated report as a PDF attachment. Deliberately a separate
// step from generate: re-sending an existing report must not rebuild it (the numbers
// in a saved report are frozen, and rebuilding would silently change them).
//
// Recipient defaults to the user who asked for it, resolved from the row — so this
// can't be turned into a way to mail arbitrary addresses.
async function email(id, { toUserId } = {}) {
  const row = await getRaw(id);
  if (!row) throw badRequest("Report not found.");
  if (row.status !== "generated" || !row.file_path) {
    throw badRequest("Report is not ready to send yet.");
  }
  if (!emailService.isEnabled()) {
    const err = new Error("Email is not configured on this server (SMTP_USER / SMTP_PASS).");
    err.status = 503;
    throw err;
  }

  const [[user]] = await db.query("SELECT email, name FROM users WHERE user_id = ? LIMIT 1", [
    toUserId ?? row.generated_by,
  ]);
  if (!user?.email) throw badRequest("No email address on file for that user.");

  const file = await fileFor(id, "pdf");
  if (!file) throw badRequest("Report PDF is missing — regenerate it.");

  const ok = await emailService.sendReportEmail(
    user.email,
    {
      title: row.title,
      typeLabel: TYPE_LABEL[row.type] ?? row.type,
      periodStart: row.period_start,
      periodEnd: row.period_end,
      deviceName: row.device_name ?? null,
      generatedByName: row.generated_by_name ?? null,
      filename: file.downloadName,
    },
    fs.readFileSync(file.absPath),
  );
  if (!ok) {
    const err = new Error("The email provider rejected the message.");
    err.status = 502;
    throw err;
  }
  // `report` rides along so the route can audit WHAT was sent, not just "#<id>".
  return { sentTo: user.email, report: toClient(row) };
}

// Retention: drop reports older than `days` — the MySQL row AND both files. Goes
// through remove() so the path-traversal guard and unlink stay one code path.
//
// Deleting the row (rather than only the file) is deliberate: a row whose file is
// gone renders as a download that 404s, which is worse than no row at all. The
// default is longer than the alerts one (NOTIFY_RETENTION_DAYS, 30) because a
// report is an artifact somebody deliberately asked for, not an auto-raised alert.
async function purgeOld(days) {
  // NOT `Number(days) || 90` — 0 is falsy, so that silently turns "purge everything"
  // into "keep 90 days", which is the opposite instruction. 0 is a legitimate value.
  const raw = Number(days);
  const n = Number.isFinite(raw) && raw >= 0 ? raw : 90;
  const [rows] = await db.query(
    "SELECT report_id FROM reports WHERE created_at < (NOW() - INTERVAL ? DAY)",
    [n],
  );
  let removed = 0;
  for (const r of rows) {
    // silent: the nightly purge would otherwise fire one socket event per row at 3am.
    // Nobody is watching, and a page opened later loads the correct list anyway.
    if (await remove(r.report_id, { silent: true })) removed++;
  }
  return removed;
}

export default {
  init, list, create, build, generate, fileFor, remove, purgeOld, scopeOptions, email,
  REPORT_TYPES, SCOPE_TYPES,
};
