-- MySQL Script generated by MySQL Workbench
-- Thu May  7 13:09:53 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema server_monitoring_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema server_monitoring_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `server_monitoring_system` DEFAULT CHARACTER SET utf8 ;
USE `server_monitoring_system` ;

-- -----------------------------------------------------
-- Table `server_monitoring_system`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `hash_password` VARCHAR(255) NOT NULL,
  `role` ENUM('admin', 'it_staff') NOT NULL,
  `profile_image` VARCHAR(255) NULL,
  `status` ENUM('active', 'inactive') NULL,
  `last_login` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `idx_users_email` (`email` ASC),
  UNIQUE INDEX `idx_users_username` (`username` ASC),
  INDEX `idx_user_role` (`role` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`devices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`devices` (
  `id` INT NOT NULL,
  `device_name` VARCHAR(100) NOT NULL,
  `device_ip` VARCHAR(100) NULL,
  `device_type` ENUM('aircon', 'server', 'sensor') NOT NULL,
  `status` ENUM('online', 'offline') NULL,
  `location` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_devices_status` (`status` ASC),
  INDEX `idx_devices_type` (`device_type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`ir_commands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`ir_commands` (
  `ir_command_id` INT NOT NULL AUTO_INCREMENT,
  `devices_id` INT NOT NULL,
  `command_name` VARCHAR(50) NOT NULL,
  `raw_signal` VARCHAR(255) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `status` ENUM('active', 'inactive') NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ir_command_id`),
  INDEX `idx_ir_commands_device` (`devices_id` ASC),
  UNIQUE INDEX `command_name_UNIQUE` (`command_name` ASC),
  CONSTRAINT `fk_ir_commands_devices2`
    FOREIGN KEY (`devices_id`)
    REFERENCES `server_monitoring_system`.`devices` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`alert_rules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`alert_rules` (
  `alert_rule_id` INT NOT NULL AUTO_INCREMENT,
  `devices_id` INT NOT NULL,
  `metric_name` VARCHAR(50) NOT NULL,
  `treshold_value` FLOAT NOT NULL,
  `comparison` ENUM('>', '<', '>=', '<=', '=') NOT NULL,
  `severity` ENUM('critical', 'warning', 'info') NOT NULL,
  `is_active` TINYINT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`alert_rule_id`),
  INDEX `idx_rules_device` (`devices_id` ASC),
  INDEX `idx_rules_active` (`is_active` ASC),
  INDEX `idx_rules_dev_active` (`devices_id` ASC, `is_active` ASC),
  CONSTRAINT `fk_alert_rules_devices2`
    FOREIGN KEY (`devices_id`)
    REFERENCES `server_monitoring_system`.`devices` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`alerts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`alerts` (
  `alert_id` INT NOT NULL AUTO_INCREMENT,
  `devices_id` INT NOT NULL,
  `alert_rule_id` INT NOT NULL,
  `acknowledged_by` INT NOT NULL,
  `metric_value` FLOAT NOT NULL,
  `type` VARCHAR(100) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `message` TEXT(255) NOT NULL,
  `severity` ENUM('critical', 'warning', 'info') NOT NULL,
  `status` ENUM('active', 'acknowledged', 'resolved') NOT NULL,
  `acknowledged_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `resolved_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`alert_id`),
  INDEX `fk_alerts_alert_rules1_idx` (`alert_rule_id` ASC),
  INDEX `idx_alerts_device` (`devices_id` ASC),
  INDEX `fk_alerts_users1_idx` (`acknowledged_by` ASC),
  INDEX `idx_alerts_status` (`status` ASC),
  INDEX `idx_alerts_severity` (`severity` ASC),
  INDEX `idx_alerts_created` (`created_at` ASC),
  INDEX `idx_alerts_dev_stat` (`devices_id` ASC, `status` ASC),
  CONSTRAINT `fk_alerts_alert_rules1`
    FOREIGN KEY (`alert_rule_id`)
    REFERENCES `server_monitoring_system`.`alert_rules` (`alert_rule_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_alerts_devices2`
    FOREIGN KEY (`devices_id`)
    REFERENCES `server_monitoring_system`.`devices` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_alerts_users1`
    FOREIGN KEY (`acknowledged_by`)
    REFERENCES `server_monitoring_system`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`system_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`system_logs` (
  `system_log_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `action` VARCHAR(255) NOT NULL,
  `description` TEXT(255) NOT NULL,
  `ip_address` VARCHAR(255) NULL,
  `module` ENUM('auth', 'aircon', 'users', 'alerts', 'reports') NULL,
  `user_agent` VARCHAR(255) NULL,
  `log_level` ENUM('info', 'warning', 'error') NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`system_log_id`),
  INDEX `idx_syslogs_user` (`user_id` ASC),
  INDEX `idx_syslogs_created` (`created_at` ASC),
  INDEX `idx_syslogs_module` (`module` ASC),
  CONSTRAINT `fk_system_logs_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `server_monitoring_system`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`device_metrics_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`device_metrics_config` (
  `id` INT NOT NULL,
  `devices_id` INT NOT NULL,
  `metric_name` VARCHAR(100) NOT NULL,
  `unit` VARCHAR(100) NULL,
  `threshold_max` INT NULL,
  `threshold_min` INT NULL,
  `polling_interval` INT NULL,
  `is_enabled` TINYINT NULL,
  `description` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_metrics_cfg_device` (`devices_id` ASC),
  INDEX `idx_metrics_cfg_enabled` (`is_enabled` ASC),
  CONSTRAINT `fk_device_metrics_config_devices2`
    FOREIGN KEY (`devices_id`)
    REFERENCES `server_monitoring_system`.`devices` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`reports` (
  `id` INT NOT NULL,
  `generated_by` INT NOT NULL,
  `title` VARCHAR(100) NULL,
  `type` ENUM('environment', 'server', 'alerts', 'aircon') NULL,
  `status` ENUM('pending', 'generated', 'failed') NULL,
  `file_path` TEXT(255) NULL,
  `period_start` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `period_end` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_reports_by` (`generated_by` ASC),
  INDEX `idx_reports_status` (`status` ASC),
  INDEX `idx_reports_created` (`created_at` ASC),
  CONSTRAINT `fk_reports_users1`
    FOREIGN KEY (`generated_by`)
    REFERENCES `server_monitoring_system`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`server_specs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`server_specs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `devices_id` INT NOT NULL,
  `os` VARCHAR(100) NOT NULL,
  `kernel` VARCHAR(100) NOT NULL,
  `cores` INT NOT NULL,
  `architecture` VARCHAR(100) NOT NULL,
  `memory_total_mb` BIGINT NULL,
  `disk_total_gb` BIGINT NULL,
  `uptime` VARCHAR(50) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_server_specs_device` (`devices_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_server_specs_devices1`
    FOREIGN KEY (`devices_id`)
    REFERENCES `server_monitoring_system`.`devices` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`device_network`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`device_network` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `devices_id` INT NOT NULL,
  `ip_address` VARCHAR(100) NOT NULL,
  `gateway` VARCHAR(100) NOT NULL,
  `dns` VARCHAR(100) NOT NULL,
  `region` VARCHAR(100) NOT NULL,
  `mac_address` VARCHAR(255) NULL,
  `snmp_port` INT NULL,
  `snmp_community` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_device_network_devices1_idx` (`devices_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_device_network_devices1`
    FOREIGN KEY (`devices_id`)
    REFERENCES `server_monitoring_system`.`devices` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`aircon_state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`aircon_state` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `devices_id` INT NOT NULL,
  `mode` ENUM('cool', 'auto', 'fan') NULL,
  `set_temperature` INT NULL,
  `fan_mode` VARCHAR(45) NULL,
  `is_on` TINYINT NULL,
  `last_trigger` ENUM('auto', 'schedule') NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_aircon_state_device` (`devices_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_aircon_state_devices1`
    FOREIGN KEY (`devices_id`)
    REFERENCES `server_monitoring_system`.`devices` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`alert_notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`alert_notifications` (
  `notification_id` INT NOT NULL,
  `alert_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `is_read` TINYINT NOT NULL,
  `sent-at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `read_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`notification_id`),
  INDEX `idx_notif_alert` (`alert_id` ASC),
  INDEX `idx_notif_user` (`user_id` ASC),
  INDEX `idx_notif_user_read` (`user_id` ASC, `is_read` ASC),
  CONSTRAINT `fk_alert_notifications_alerts1`
    FOREIGN KEY (`alert_id`)
    REFERENCES `server_monitoring_system`.`alerts` (`alert_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_alert_notifications_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `server_monitoring_system`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`aircon_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`aircon_logs` (
  `id` INT NOT NULL,
  `devices_id` INT NOT NULL,
  `action` VARCHAR(255) NOT NULL,
  `reason` VARCHAR(255) NOT NULL,
  `trigger_type` ENUM('auto', 'schedule') NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_aircon_logs_device` (`devices_id` ASC),
  INDEX `idx_aircon_logs_created` (`created_at` ASC),
  CONSTRAINT `fk_aircon_logs_devices1`
    FOREIGN KEY (`devices_id`)
    REFERENCES `server_monitoring_system`.`devices` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`settings` (
  `settings_id` INT NOT NULL,
  `updated_by` INT NOT NULL,
  `setting_key` VARCHAR(255) NULL,
  `setting_value` TEXT(255) NULL,
  `description` VARCHAR(255) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`settings_id`),
  INDEX `fk_settings_users1_idx` (`updated_by` ASC),
  CONSTRAINT `fk_settings_users1`
    FOREIGN KEY (`updated_by`)
    REFERENCES `server_monitoring_system`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`report` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `generated_by` INT NOT NULL,
  `title` VARCHAR(100) NULL,
  `type` VARCHAR(100) NULL,
  `status` ENUM('pending', 'geneated', 'failed') NULL,
  `file_path` TEXT NULL,
  `period_start` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `period_end` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_reports_by` (`generated_by` ASC),
  INDEX `idx_reports_status` (`status` ASC),
  INDEX `idx_reports_created` (`created_at` ASC),
  CONSTRAINT `fk_report_users1`
    FOREIGN KEY (`generated_by`)
    REFERENCES `server_monitoring_system`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`role_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`role_permissions` (
  `role` ENUM('admin', 'it_staff') NOT NULL,
  `permission_id` INT NOT NULL,
  INDEX `fk_role_permissions_permissions1_idx` (`permission_id` ASC),
  CONSTRAINT `fk_role_permissions_permissions1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `server_monitoring_system`.`permissions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
