-- MySQL Script generated by MySQL Workbench
-- Thu Jun  4 19:46:28 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema server_monitoring_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema server_monitoring_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `server_monitoring_system` DEFAULT CHARACTER SET utf8 ;
USE `server_monitoring_system` ;

-- -----------------------------------------------------
-- Table `server_monitoring_system`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `avatar` VARCHAR(10) NULL,
  `hash_password` VARCHAR(255) NOT NULL,
  `role` ENUM('admin', 'it_staff') NOT NULL,
  `profile_image` VARCHAR(255) NULL,
  `status` ENUM('active', 'inactive') NULL,
  -- F-02: bumped on logout / disable / role change / password change to
  -- invalidate any still-valid JWT whose `tv` claim no longer matches.
  `token_version` INT NOT NULL DEFAULT 0,
  `last_login` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `idx_users_email` (`email` ASC),
  UNIQUE INDEX `idx_users_username` (`username` ASC),
  INDEX `idx_user_role` (`role` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`devices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`devices` (
  `device_id` INT NOT NULL AUTO_INCREMENT,
  `ip_address` VARCHAR(100) NULL,
  `device_name` VARCHAR(100) NOT NULL,
  `device_type` ENUM('aircon', 'server', 'ups', 'router', 'esp32') NOT NULL,
  `status` ENUM('online', 'offline', 'warning', 'maintenance') NULL,
  `location` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`device_id`),
  INDEX `idx_devices_status` (`status` ASC),
  INDEX `idx_devices_type` (`device_type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`ir_commands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`ir_commands` (
  `ir_command_id` INT NOT NULL AUTO_INCREMENT,
  `device_id` INT NOT NULL,
  `command_name` VARCHAR(50) NOT NULL,
  `raw_signal` VARCHAR(255) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `status` ENUM('active', 'inactive') NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ir_command_id`),
  INDEX `fk_ir_commands_devices_idx` (`device_id` ASC),
  UNIQUE INDEX `idx_ir_cmd_device_name` (`device_id` ASC, `command_name` ASC),
  CONSTRAINT `fk_ir_commands_devices1`
    FOREIGN KEY (`device_id`)
    REFERENCES `server_monitoring_system`.`devices` (`device_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`alert_rules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`alert_rules` (
  `alert_rule_id` INT NOT NULL AUTO_INCREMENT,
  `device_id` INT NOT NULL,
  `metric_name` VARCHAR(50) NOT NULL,
  `threshold_value` FLOAT NOT NULL,
  `comparison` ENUM('>', '<', '>=', '<=', '=') NOT NULL,
  `severity` ENUM('critical', 'warning', 'info') NOT NULL,
  `is_active` TINYINT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`alert_rule_id`),
  INDEX `idx_rules_device` (`device_id` ASC),
  INDEX `idx_rules_active` (`is_active` ASC),
  INDEX `idx_rules_dev_active` (`device_id` ASC, `is_active` ASC),
  CONSTRAINT `fk_alert_rules_devices2`
    FOREIGN KEY (`device_id`)
    REFERENCES `server_monitoring_system`.`devices` (`device_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`alerts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`alerts` (
  `alert_id` INT NOT NULL AUTO_INCREMENT,
  `device_id` INT NOT NULL,
  `alert_rule_id` INT NULL,
  `acknowledged_by` INT NULL,
  `metric_value` FLOAT NOT NULL,
  `type` VARCHAR(100) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `message` TEXT(255) NOT NULL,
  `severity` ENUM('critical', 'warning', 'info') NOT NULL,
  `status` ENUM('active', 'acknowledged', 'resolved') NOT NULL,
  `acknowledged_at` TIMESTAMP NULL,
  `resolved_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`alert_id`),
  INDEX `fk_alerts_alert_rules1_idx` (`alert_rule_id` ASC),
  INDEX `idx_alerts_device` (`device_id` ASC),
  INDEX `fk_alerts_users1_idx` (`acknowledged_by` ASC),
  INDEX `idx_alerts_status` (`status` ASC),
  INDEX `idx_alerts_severity` (`severity` ASC),
  INDEX `idx_alerts_created` (`created_at` ASC),
  INDEX `idx_alerts_dev_stat` (`device_id` ASC, `status` ASC),
  CONSTRAINT `fk_alerts_alert_rules1`
    FOREIGN KEY (`alert_rule_id`)
    REFERENCES `server_monitoring_system`.`alert_rules` (`alert_rule_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_alerts_devices2`
    FOREIGN KEY (`device_id`)
    REFERENCES `server_monitoring_system`.`devices` (`device_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_alerts_users1`
    FOREIGN KEY (`acknowledged_by`)
    REFERENCES `server_monitoring_system`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`system_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`system_logs` (
  `system_log_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `action` VARCHAR(255) NOT NULL,
  `description` TEXT(255) NOT NULL,
  `ip_address` VARCHAR(255) NULL,
  `module` ENUM('auth', 'aircon', 'users', 'alerts', 'reports', 'devices', 'network') NULL,
  `user_agent` VARCHAR(255) NULL,
  `log_level` ENUM('info', 'warning', 'error') NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`system_log_id`),
  INDEX `idx_syslogs_user` (`user_id` ASC),
  INDEX `idx_syslogs_created` (`created_at` ASC),
  INDEX `idx_syslogs_module` (`module` ASC),
  CONSTRAINT `fk_system_logs_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `server_monitoring_system`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`device_metrics_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`device_metrics_config` (
  `metric_config_id` INT NOT NULL AUTO_INCREMENT,
  `device_id` INT NOT NULL,
  `metric_name` VARCHAR(100) NOT NULL,
  `unit` VARCHAR(100) NULL,
  `threshold_max` FLOAT NULL,
  `threshold_min` FLOAT NULL,
  `polling_interval_sec` INT NULL,
  `is_enabled` TINYINT NULL,
  `description` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`metric_config_id`),
  INDEX `idx_metrics_cfg_device` (`device_id` ASC),
  INDEX `idx_metrics_cfg_enabled` (`is_enabled` ASC),
  CONSTRAINT `fk_device_metrics_config_devices2`
    FOREIGN KEY (`device_id`)
    REFERENCES `server_monitoring_system`.`devices` (`device_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`reports` (
  `report_id` INT NOT NULL AUTO_INCREMENT,
  `generated_by` INT NOT NULL,
  `title` VARCHAR(100) NULL,
  `type` ENUM('environment', 'server', 'alerts', 'aircon', 'network', 'ups') NULL,
  `status` ENUM('pending', 'generated', 'failed') NULL,
  `file_path` VARCHAR(255) NULL,
  `period_start` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `period_end` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`report_id`),
  INDEX `idx_reports_by` (`generated_by` ASC),
  INDEX `idx_reports_status` (`status` ASC),
  INDEX `idx_reports_created` (`created_at` ASC),
  CONSTRAINT `fk_reports_users1`
    FOREIGN KEY (`generated_by`)
    REFERENCES `server_monitoring_system`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`server_specs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`server_specs` (
  `server_spec_id` INT NOT NULL AUTO_INCREMENT,
  `device_id` INT NOT NULL,
  `os` VARCHAR(100) NOT NULL,
  `kernel` VARCHAR(100) NOT NULL,
  `cores` INT NOT NULL,
  `architecture` VARCHAR(100) NOT NULL,
  `memory_total_mb` BIGINT NULL,
  `disk_total_gb` BIGINT NULL,
  `uptime` VARCHAR(50) NULL,
  `agent_version` VARCHAR(20) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `last_seen` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_server_specs_device` (`device_id` ASC),
  PRIMARY KEY (`server_spec_id`),
  UNIQUE INDEX `devices_id_UNIQUE` (`device_id` ASC),
  CONSTRAINT `fk_server_specs_devices1`
    FOREIGN KEY (`device_id`)
    REFERENCES `server_monitoring_system`.`devices` (`device_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`device_network`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`device_network` (
  `network_id` INT NOT NULL AUTO_INCREMENT,
  `device_id` INT NOT NULL,
  `gateway` VARCHAR(100) NOT NULL,
  `dns` VARCHAR(100) NOT NULL,
  `network_segment` VARCHAR(100) NOT NULL,
  `mac_address` VARCHAR(255) NULL,
  `snmp_port` INT NULL,
  `snmp_community` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_device_network_devices1_idx` (`device_id` ASC),
  PRIMARY KEY (`network_id`),
  UNIQUE INDEX `devices_id_UNIQUE` (`device_id` ASC),
  CONSTRAINT `fk_device_network_devices1`
    FOREIGN KEY (`device_id`)
    REFERENCES `server_monitoring_system`.`devices` (`device_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`aircon_state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`aircon_state` (
  `aircon_state_id` INT NOT NULL AUTO_INCREMENT,
  `device_id` INT NOT NULL,
  `ir_channel` TINYINT NULL DEFAULT 1,
  `triggered_by_user_id` INT NULL,
  `mode` ENUM('cool', 'auto', 'fan') NULL,
  `set_temperature` INT NULL,
  `fan_mode` VARCHAR(45) NULL,
  `is_on` TINYINT NULL,
  `last_trigger` ENUM('manual', 'auto', 'schedule') NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE INDEX `idx_aircon_state_device` (`device_id` ASC),
  PRIMARY KEY (`aircon_state_id`),
  INDEX `fk_aircon_state_users1_idx` (`triggered_by_user_id` ASC),
  UNIQUE INDEX `idx_aircon_ir_channel` (`ir_channel` ASC),
  CONSTRAINT `fk_aircon_state_devices1`
    FOREIGN KEY (`device_id`)
    REFERENCES `server_monitoring_system`.`devices` (`device_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_aircon_state_users1`
    FOREIGN KEY (`triggered_by_user_id`)
    REFERENCES `server_monitoring_system`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`alert_notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`alert_notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `alert_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `is_read` TINYINT NOT NULL,
  `sent_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `read_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_notif_alert` (`alert_id` ASC),
  INDEX `idx_notif_user` (`user_id` ASC),
  INDEX `idx_notif_user_read` (`user_id` ASC, `is_read` ASC),
  CONSTRAINT `fk_alert_notifications_alerts1`
    FOREIGN KEY (`alert_id`)
    REFERENCES `server_monitoring_system`.`alerts` (`alert_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_alert_notifications_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `server_monitoring_system`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`aircon_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`aircon_logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `device_id` INT NOT NULL,
  `user_id` INT NULL,
  `action` VARCHAR(255) NOT NULL,
  `reason` VARCHAR(255) NOT NULL,
  `trigger_type` ENUM('manual', 'auto', 'schedule') NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_aircon_logs_device` (`device_id` ASC),
  INDEX `idx_aircon_logs_created` (`created_at` ASC),
  INDEX `fk_aircon_logs_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_aircon_logs_devices1`
    FOREIGN KEY (`device_id`)
    REFERENCES `server_monitoring_system`.`devices` (`device_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_aircon_logs_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `server_monitoring_system`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`settings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `updated_by` INT NULL,
  `setting_key` VARCHAR(255) NULL,
  `setting_value` TEXT(255) NULL,
  `description` VARCHAR(255) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_settings_users1_idx` (`updated_by` ASC),
  UNIQUE INDEX `idx_settings_key` (`setting_key` ASC),
  CONSTRAINT `fk_settings_users1`
    FOREIGN KEY (`updated_by`)
    REFERENCES `server_monitoring_system`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`agent_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`agent_tokens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `device_id` INT NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `approved_token` VARCHAR(128) NULL,
  `status` ENUM('pending', 'approved', 'rejected') NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_used_at` DATETIME NOT NULL,
  `approved_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_agent_tokens_devices1_idx` (`device_id` ASC),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC),
  UNIQUE INDEX `approved_token_UNIQUE` (`approved_token` ASC),
  CONSTRAINT `fk_agent_tokens_devices1`
    FOREIGN KEY (`device_id`)
    REFERENCES `server_monitoring_system`.`devices` (`device_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`sensor_backup_batches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`sensor_backup_batches` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `device_id` INT NOT NULL,
  `total_rows` INT NULL,
  `period_start` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `period_end` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `status` ENUM('received', 'processed', 'failed') NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_sensor_backup_batches_devices1_idx` (`device_id` ASC),
  CONSTRAINT `fk_sensor_backup_batches_devices1`
    FOREIGN KEY (`device_id`)
    REFERENCES `server_monitoring_system`.`devices` (`device_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`network_interfaces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`network_interfaces` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `device_id` INT NOT NULL,
  `interface_name` VARCHAR(50) NULL,
  `location_label` VARCHAR(100) NULL,
  `is_active` TINYINT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_network_interfaces_devices1_idx` (`device_id` ASC),
  CONSTRAINT `fk_network_interfaces_devices1`
    FOREIGN KEY (`device_id`)
    REFERENCES `server_monitoring_system`.`devices` (`device_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`suggestions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`suggestions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `device_id` INT NULL,
  `dismissed_by` INT NULL,
  `domain` ENUM('environment', 'server', 'network', 'ups') NOT NULL,
  `title` VARCHAR(150) NOT NULL,
  `message` TEXT NULL,
  `trigger_metric` VARCHAR(100) NOT NULL,
  `trigger_value` FLOAT NOT NULL,
  `priority` ENUM('high', 'medium', 'low') NOT NULL,
  `status` ENUM('open', 'dismissed', 'acted') NOT NULL,
  `dismissed_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_suggestions_devices1_idx` (`device_id` ASC),
  INDEX `fk_suggestions_users1_idx` (`dismissed_by` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_suggestions_devices1`
    FOREIGN KEY (`device_id`)
    REFERENCES `server_monitoring_system`.`devices` (`device_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_suggestions_users1`
    FOREIGN KEY (`dismissed_by`)
    REFERENCES `server_monitoring_system`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`mikrotik_devices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`mikrotik_devices` (
  `mikrotik_id` INT NOT NULL AUTO_INCREMENT,
  `device_id` INT NOT NULL,
  `routeros_version` VARCHAR(50) NULL,
  `board_model` VARCHAR(100) NULL,
  `firmware_version` VARCHAR(50) NULL,
  `api_port` INT NULL DEFAULT 8728,
  `api_username` VARCHAR(100) NULL,
  `api_password` VARCHAR(255) NULL,
  `api_enabled` TINYINT NULL DEFAULT 1,
  `last_seen` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`mikrotik_id`),
  INDEX `fk_mikrotik_devices_devices1_idx` (`device_id` ASC),
  UNIQUE INDEX `devices_id_UNIQUE` (`device_id` ASC),
  CONSTRAINT `fk_mikrotik_devices_devices1`
    FOREIGN KEY (`device_id`)
    REFERENCES `server_monitoring_system`.`devices` (`device_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`ups_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`ups_details` (
  `ups_detail_id` INT NOT NULL AUTO_INCREMENT,
  `device_id` INT NOT NULL,
  `brand` VARCHAR(100) NULL,
  `model` VARCHAR(100) NULL,
  `battery_capacity` VARCHAR(50) NULL,
  `communication_type` ENUM('usb', 'snmp', 'serial', 'network') NULL,
  `serial_number` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ups_detail_id`),
  INDEX `fk_ups_details_devices1_idx` (`device_id` ASC),
  UNIQUE INDEX `devices_id_UNIQUE` (`device_id` ASC),
  CONSTRAINT `fk_ups_details_devices1`
    FOREIGN KEY (`device_id`)
    REFERENCES `server_monitoring_system`.`devices` (`device_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_monitoring_system`.`device_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `server_monitoring_system`.`device_logs` (
  `device_log_id` INT NOT NULL AUTO_INCREMENT,
  `device_id` INT NOT NULL,
  `log_level` ENUM('info', 'warning', 'critical', 'error') NULL,
  `message` TEXT NULL,
  `recorded_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`device_log_id`),
  INDEX `fk_device_logs_devices1_idx` (`device_id` ASC),
  CONSTRAINT `fk_device_logs_devices1`
    FOREIGN KEY (`device_id`)
    REFERENCES `server_monitoring_system`.`devices` (`device_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- F-02 MIGRATION: users.token_version (session revocation)
-- -----------------------------------------------------
-- The `users` CREATE TABLE above already includes `token_version`, so a FRESH
-- import needs nothing here. This block is for an EXISTING database created
-- before that column was added (e.g. run it from the phpMyAdmin SQL tab).
-- It is idempotent: it only adds the column if it does not already exist, so
-- re-importing this whole file will not raise a "duplicate column" error.
-- Uses DATABASE() so it targets whichever database is currently selected
-- (e.g. `cspc-ictu-monitoring-system`), regardless of the schema name used
-- in the CREATE TABLE statements above.
SET @col_exists := (
  SELECT COUNT(*) FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME   = 'users'
    AND COLUMN_NAME  = 'token_version'
);
SET @ddl := IF(@col_exists = 0,
  'ALTER TABLE `users` ADD COLUMN `token_version` INT NOT NULL DEFAULT 0 AFTER `status`',
  'DO 0');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Plain equivalent (use this single line instead if you prefer; it will error
-- only if the column already exists). Adjust the backticked DB name to match
-- the database you import into:
--   ALTER TABLE `cspc-ictu-monitoring-system`.`users`
--     ADD COLUMN `token_version` INT NOT NULL DEFAULT 0 AFTER `status`;
